# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'realm_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for realm_demo
#    pod 'Realm', '~> 10.5.0'
  pod 'RealmSwift', '~> 10.5.0'


  target 'realm_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'realm_demoUITests' do
    # Pods for testing
  end

end
